[workspace]
members = ["escrow-engine"]
resolver = "3"

# workspace name
[workspace.package]
name = "eltris"

[workspace.dependencies]

bitcoin = "0.31"
secp256k1 = { version = "0.28", features = ["rand"] }
sha2 = "0.10"
hex = "0.4"
nostr-sdk = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
ldk-node = "0.6.2"